stages:
  - deploy

push_master_to_github:
  stage: deploy
  tags:
    - internet
  only:
    - master
    - /^release\/v/
    - /^v\d+\.\d+/
#  when: on_success
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  variables:
    GIT_DEPTH: 0
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GH_PUSH_KEY > ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git remote add github git@github.com:espressif/esp32-bt-lib.git
    # Ref: esp-idf tools/ci/push_to_github.sh
    - |
      if [ -n "${CI_COMMIT_TAG}" ]; then
        git push github "${CI_COMMIT_TAG}"
      else
        git push github "${CI_COMMIT_SHA}:refs/heads/${CI_COMMIT_REF_NAME}"
      fi
